### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Guixaviertga** [ybd-project/ytdl-core#23]
SUCCESS ]: Successfully generated a poToken.
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of TypeError
    at Object.writeFileSync (node:fs:2350:5)
    at Gui (/storage/emulated/0/X-BOT-MD/Lukaz.js:1188:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of TypeError
    at Object.writeFileSync (node:fs:2350:5)
    at Gui (/storage/emulated/0/X-BOT-MD/Lukaz.js:1188:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of TypeError
    at Object.writeFileSync (node:fs:2350:5)
    at Gui (/storage/emulated/0/X-BOT-MD/Lukaz.js:1188:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_A 
in termux it works, in the panel it doesn't work

**Comment by ybd-project** [comment]
Please tell us what code you are implementing, the OS type and version, the Node.js version, and the version of ytdl-core you are using.
