### ISSUE TITLE
Error: highest default value when no format is chosen doesn't exist on certain videos

### ISSUE THREAD

**Issue by gabrielschull** [ybd-project/ytdl-core#45]
"Error: Error: No such format found: highest
    at FormatUtils.chooseFormat (/workspace/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:914:23829)
    at /workspace/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:915:624
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at console.error (/workspace/node_modules/firebase-functions/lib/logger/compat.js:31:23)
    at sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:33:17)
    at Domain.errorHandler (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:93:48)
    at Domain.emit (node:events:519:28)
    at Domain.emit (node:domain:488:12)
    at emitUnhandledRejection (node:internal/process/promises:249:24)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"

**Comment by gabrielschull** [comment]
Is there a value to pass that will be universally accepted? What else can be defaulted to?

**Comment by s123121** [comment]
this is an error when ytdl can not get any format. You either:
- rotate poToken & vistiorData to try again
- use oAuth 
- use proxy (check example)

and try again, also please check other video (some video is just buggy)

**Comment by gabrielschull** [comment]
> this is an error when ytdl can not get any format. You either:
> 
> * rotate poToken & vistiorData to try again
> * use oAuth
> * use proxy (check example)
> 
> and try again, also please check other video (some video is just buggy)

Thanks for the reply

**Comment by tiago719** [comment]
I'm consistently having this exception for multiple videos. How can I Fix it? I'm already using a proxy.

**Comment by gabrielschull** [comment]
> I'm consistently having this exception for multiple videos. How can I Fix it? I'm already using a proxy.

You can find the video data with getInfo.
Explicitly choose the formats where qualityLabel (video) and audioBitrate (audio) are highest - I split audio/video streams before joining them. Also check out distube/ytdl-core.
